# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d30060be81272a3febcbb301a4df28627b44d00f1f603330bea3062a8f1af14117c1aca766e3ea810bac259d06c763ded373697649f756da9077dda2d5db83f

test:
  secret_key_base: 342f09887c283cc9bd9e27373290bd15ba2e827b9ab2b69b456316b82321820aafd6a021bd725c403fd5df8370119cce73e9c93b49ef094b2399b30dac8d42d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
